[package]
name = "luau-format-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.31.1", features = ["wgpu"] }
egui_code_editor = "0.2.13"
reqwest = "0.12.18"
rfd = "0.15.3"
tokio = { version = "1.45.1", features = ["full"] }
